# Generated by Django 4.2.7 on 2023-11-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ap_pat', models.CharField(max_length=80)),
                ('ap_mat', models.CharField(max_length=80)),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
